//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace xMax.Module.BusinessObjects
{

    [MapInheritance(MapInheritanceType.OwnTable)]
    public partial class Apparato : Articolo
    {
        [Association(@"ApparatoReferencesArticolo")]
        public XPCollection<Articolo> Ricambi { get { return GetCollection<Articolo>(nameof(Ricambi)); } }
        [Association(@"InstallazioneReferencesApparato")]
        public XPCollection<Installazione> Installazioni { get { return GetCollection<Installazione>(nameof(Installazioni)); } }
    }

}
