//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace xMax.Module.BusinessObjects
{

    public partial class Articolo : BaseXPObject
    {
        string fDescrizione;
        public string Descrizione
        {
            get { return fDescrizione; }
            set { SetPropertyValue<string>(nameof(Descrizione), ref fDescrizione, value); }
        }
        TipoArticolo fTipoArticolo;
        [Association(@"ArticoloReferencesTipoArticolo")]
        [DevExpress.Persistent.Base.ImmediatePostData]
        public TipoArticolo TipoArticolo
        {
            get { return fTipoArticolo; }
            set { SetPropertyValue<TipoArticolo>(nameof(TipoArticolo), ref fTipoArticolo, value); }
        }
        Produttore fProduttore;
        public Produttore Produttore
        {
            get { return fProduttore; }
            set { SetPropertyValue<Produttore>(nameof(Produttore), ref fProduttore, value); }
        }
        string fMarca;
        public string Marca
        {
            get { return fMarca; }
            set { SetPropertyValue<string>(nameof(Marca), ref fMarca, value); }
        }
        string fModello;
        public string Modello
        {
            get { return fModello; }
            set { SetPropertyValue<string>(nameof(Modello), ref fModello, value); }
        }
        UnitaMisura fUnitaMisura;
        public UnitaMisura UnitaMisura
        {
            get { return fUnitaMisura; }
            set { SetPropertyValue<UnitaMisura>(nameof(UnitaMisura), ref fUnitaMisura, value); }
        }
        bool fVisualizzaInSchedaIntervento;
        [ColumnDefaultValue(true)]
        public bool VisualizzaInSchedaIntervento
        {
            get { return fVisualizzaInSchedaIntervento; }
            set { SetPropertyValue<bool>(nameof(VisualizzaInSchedaIntervento), ref fVisualizzaInSchedaIntervento, value); }
        }
        float fQuantitaIniziale;
        public float QuantitaIniziale
        {
            get { return fQuantitaIniziale; }
            set { SetPropertyValue<float>(nameof(QuantitaIniziale), ref fQuantitaIniziale, value); }
        }
        decimal fCostoUnitario;
        public decimal CostoUnitario
        {
            get { return fCostoUnitario; }
            set { SetPropertyValue<decimal>(nameof(CostoUnitario), ref fCostoUnitario, value); }
        }
        [Association(@"ApparatoReferencesArticolo")]
        public XPCollection<Apparato> Apparati { get { return GetCollection<Apparato>(nameof(Apparati)); } }
        [DevExpress.ExpressApp.Model.ModelDefault("AllowEdit", "False")]
        [Association(@"FornitoreArticoloReferencesArticolo")]
        public XPCollection<FornitoreArticolo> Fornitori { get { return GetCollection<FornitoreArticolo>(nameof(Fornitori)); } }
        [DevExpress.ExpressApp.Model.ModelDefault("AllowEdit", "False")]
        [MemberDesignTimeVisibility(false)]
        [Association(@"DDTAcquistoElencoMaterialeReferencesArticolo")]
        public XPCollection<DDTAcquistoElencoMateriale> DDTAcquistoArticolo { get { return GetCollection<DDTAcquistoElencoMateriale>(nameof(DDTAcquistoArticolo)); } }
        [DevExpress.ExpressApp.Model.ModelDefault("AllowEdit", "False")]
        [MemberDesignTimeVisibility(false)]
        [Association(@"DDTVenditaElencoMaterialeReferencesArticolo")]
        public XPCollection<DDTVenditaElencoMateriale> DDTVenditaArticolo { get { return GetCollection<DDTVenditaElencoMateriale>(nameof(DDTVenditaArticolo)); } }
    }

}
