//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace xMax.Module.BusinessObjects.Database
{

    public partial class Articolo : BaseXPObject
    {
        string fDescrizione;
        public string Descrizione
        {
            get { return fDescrizione; }
            set { SetPropertyValue<string>(nameof(Descrizione), ref fDescrizione, value); }
        }
        TipoArticolo fTipoApparato;
        public TipoArticolo TipoApparato
        {
            get { return fTipoApparato; }
            set { SetPropertyValue<TipoArticolo>(nameof(TipoApparato), ref fTipoApparato, value); }
        }
        Produttore fProduttore;
        public Produttore Produttore
        {
            get { return fProduttore; }
            set { SetPropertyValue<Produttore>(nameof(Produttore), ref fProduttore, value); }
        }
        string fMarca;
        public string Marca
        {
            get { return fMarca; }
            set { SetPropertyValue<string>(nameof(Marca), ref fMarca, value); }
        }
        string fModello;
        public string Modello
        {
            get { return fModello; }
            set { SetPropertyValue<string>(nameof(Modello), ref fModello, value); }
        }
        UnitaMisura fUnitaMisura;
        public UnitaMisura UnitaMisura
        {
            get { return fUnitaMisura; }
            set { SetPropertyValue<UnitaMisura>(nameof(UnitaMisura), ref fUnitaMisura, value); }
        }
        bool fVisualizzaInSchedaIntervento;
        [ColumnDefaultValue(true)]
        public bool VisualizzaInSchedaIntervento
        {
            get { return fVisualizzaInSchedaIntervento; }
            set { SetPropertyValue<bool>(nameof(VisualizzaInSchedaIntervento), ref fVisualizzaInSchedaIntervento, value); }
        }
        int fQuantitaIniziale;
        public int QuantitaIniziale
        {
            get { return fQuantitaIniziale; }
            set { SetPropertyValue<int>(nameof(QuantitaIniziale), ref fQuantitaIniziale, value); }
        }
        [Association(@"ApparatoReferencesArticolo")]
        public XPCollection<Apparato> Apparati { get { return GetCollection<Apparato>(nameof(Apparati)); } }
        [Association(@"FornitoreArticoloReferencesArticolo")]
        public XPCollection<FornitoreArticolo> Fornitori { get { return GetCollection<FornitoreArticolo>(nameof(Fornitori)); } }
        [MemberDesignTimeVisibility(false)]
        [Association(@"DTTAcquistoElencoMaterialeReferencesArticolo")]
        public XPCollection<DDTAcquistoElencoMateriale> DTTAcquistoArticolo { get { return GetCollection<DDTAcquistoElencoMateriale>(nameof(DTTAcquistoArticolo)); } }
        [MemberDesignTimeVisibility(false)]
        [Association(@"DDTVenditaElencoMaterialeReferencesArticolo")]
        public XPCollection<DDTVenditaElencoMateriale> DDTVenditaArticolo { get { return GetCollection<DDTVenditaElencoMateriale>(nameof(DDTVenditaArticolo)); } }
    }

}
