//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace xMax.Module.BusinessObjects.Database
{

    public partial class Attrezzatura : BaseXPObject
    {
        string fDescrizione;
        public string Descrizione
        {
            get { return fDescrizione; }
            set { SetPropertyValue<string>(nameof(Descrizione), ref fDescrizione, value); }
        }
        TipoAttrezzatura fTipoAttrezzatura;
        public TipoAttrezzatura TipoAttrezzatura
        {
            get { return fTipoAttrezzatura; }
            set { SetPropertyValue<TipoAttrezzatura>(nameof(TipoAttrezzatura), ref fTipoAttrezzatura, value); }
        }
        string fMatricola;
        public string Matricola
        {
            get { return fMatricola; }
            set { SetPropertyValue<string>(nameof(Matricola), ref fMatricola, value); }
        }
        string fMarca;
        public string Marca
        {
            get { return fMarca; }
            set { SetPropertyValue<string>(nameof(Marca), ref fMarca, value); }
        }
        short fAnnoConstruzione;
        [ColumnDbDefaultValue("Null")]
        public short AnnoConstruzione
        {
            get { return fAnnoConstruzione; }
            set { SetPropertyValue<short>(nameof(AnnoConstruzione), ref fAnnoConstruzione, value); }
        }
        tipoStatoAttrezzatura fStato;
        public tipoStatoAttrezzatura Stato
        {
            get { return fStato; }
            set { SetPropertyValue<tipoStatoAttrezzatura>(nameof(Stato), ref fStato, value); }
        }
        string fMarcaturaCE;
        public string MarcaturaCE
        {
            get { return fMarcaturaCE; }
            set { SetPropertyValue<string>(nameof(MarcaturaCE), ref fMarcaturaCE, value); }
        }
        string fNote;
        [Size(2048)]
        public string Note
        {
            get { return fNote; }
            set { SetPropertyValue<string>(nameof(Note), ref fNote, value); }
        }
        [Association(@"ElencoVerificheReferencesAttrezzatura")]
        public XPCollection<ElencoVerifiche> ElencoVerifiche { get { return GetCollection<ElencoVerifiche>(nameof(ElencoVerifiche)); } }
    }

}
