//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace xMax.Module.BusinessObjects.Database
{

    public partial class BaseEvent : XPObject
    {
        string fdummy;
        [NonPersistent]
        [Browsable(false)]
        public string dummy
        {
            get { return fdummy; }
            set { SetPropertyValue<string>(nameof(dummy), ref fdummy, value); }
        }
    }

}
