//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace xMax.Module.BusinessObjects.xMaxDataModel
{

    public partial class DDT : XPObject
    {
        string fNumero;
        public string Numero
        {
            get { return fNumero; }
            set { SetPropertyValue<string>(nameof(Numero), ref fNumero, value); }
        }
        TipoDDT fTipo;
        public TipoDDT Tipo
        {
            get { return fTipo; }
            set { SetPropertyValue<TipoDDT>(nameof(Tipo), ref fTipo, value); }
        }
        Anagrafica fAnagrafica;
        public Anagrafica Anagrafica
        {
            get { return fAnagrafica; }
            set { SetPropertyValue<Anagrafica>(nameof(Anagrafica), ref fAnagrafica, value); }
        }
        [Association(@"RigaDDTReferencesDDT"), Aggregated]
        public XPCollection<RigaDDT> Righe { get { return GetCollection<RigaDDT>(nameof(Righe)); } }
    }

}
