//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace xMax.Module.BusinessObjects.Database
{

    public partial class DDTAcquisto : BaseXPObject
    {
        DateTime fData;
        public DateTime Data
        {
            get { return fData; }
            set { SetPropertyValue<DateTime>(nameof(Data), ref fData, value); }
        }
        Fornitore fFornitore;
        [Association(@"DDTAcquistoReferencesFornitore")]
        public Fornitore Fornitore
        {
            get { return fFornitore; }
            set { SetPropertyValue<Fornitore>(nameof(Fornitore), ref fFornitore, value); }
        }
        [Association(@"DDTAcquistoElencoMaterialeReferencesDDTAcquisto"), Aggregated]
        public XPCollection<DDTAcquistoElencoMateriale> ElencoMateriale { get { return GetCollection<DDTAcquistoElencoMateriale>(nameof(ElencoMateriale)); } }
    }

}
