//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace xMax.Module.BusinessObjects
{

    public partial class DDTAcquistoElencoMateriale : XPObject
    {
        DDTAcquisto fDDT;
        [Association(@"DDTAcquistoElencoMaterialeReferencesDDTAcquisto")]
        public DDTAcquisto DDT
        {
            get { return fDDT; }
            set { SetPropertyValue<DDTAcquisto>(nameof(DDT), ref fDDT, value); }
        }
        Articolo fArticolo;
        [Association(@"DTTAcquistoElencoMaterialeReferencesArticolo")]
        public Articolo Articolo
        {
            get { return fArticolo; }
            set { SetPropertyValue<Articolo>(nameof(Articolo), ref fArticolo, value); }
        }
        int fQuantita;
        public int Quantita
        {
            get { return fQuantita; }
            set { SetPropertyValue<int>(nameof(Quantita), ref fQuantita, value); }
        }
        decimal fImportoUnitario;
        public decimal ImportoUnitario
        {
            get { return fImportoUnitario; }
            set { SetPropertyValue<decimal>(nameof(ImportoUnitario), ref fImportoUnitario, value); }
        }
    }

}
