//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace xMax.Module.BusinessObjects.Database
{

    public partial class DDTVenditaElencoMateriale : XPObject
    {
        DDTVendita fDDT;
        [Association(@"DDTVenditaElencoMaterialeReferencesDDTVendita")]
        public DDTVendita DDT
        {
            get { return fDDT; }
            set { SetPropertyValue<DDTVendita>(nameof(DDT), ref fDDT, value); }
        }
        Articolo fArticolo;
        [Association(@"DDTVenditaElencoMaterialeReferencesArticolo")]
        public Articolo Articolo
        {
            get { return fArticolo; }
            set { SetPropertyValue<Articolo>(nameof(Articolo), ref fArticolo, value); }
        }
        int fQuantita;
        public int Quantita
        {
            get { return fQuantita; }
            set { SetPropertyValue<int>(nameof(Quantita), ref fQuantita, value); }
        }
        decimal fImporto;
        public decimal Importo
        {
            get { return fImporto; }
            set { SetPropertyValue<decimal>(nameof(Importo), ref fImporto, value); }
        }
    }

}
