//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace xMax.Module.BusinessObjects.Database
{

    public partial class DDTVendita : BaseXPObject
    {
        DateTime fData;
        public DateTime Data
        {
            get { return fData; }
            set { SetPropertyValue<DateTime>(nameof(Data), ref fData, value); }
        }
        Cliente fCliente;
        public Cliente Cliente
        {
            get { return fCliente; }
            set { SetPropertyValue<Cliente>(nameof(Cliente), ref fCliente, value); }
        }
        [Association(@"DDTVenditaElencoMaterialeReferencesDDTVendita"), Aggregated]
        public XPCollection<DDTVenditaElencoMateriale> ElencoMateriale { get { return GetCollection<DDTVenditaElencoMateriale>(nameof(ElencoMateriale)); } }
    }

}
