//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace xMax.Module.BusinessObjects
{

    public partial class Documento : DevExpress.Persistent.BaseImpl.FileAttachmentBase
    {
        BaseXPObject fOggettoBase;
        [Association(@"DocumentoReferencesBaseXPObject")]
        public BaseXPObject OggettoBase
        {
            get { return fOggettoBase; }
            set { SetPropertyValue<BaseXPObject>(nameof(OggettoBase), ref fOggettoBase, value); }
        }
        DateTime fDataCreazione;
        public DateTime DataCreazione
        {
            get { return fDataCreazione; }
            set { SetPropertyValue<DateTime>(nameof(DataCreazione), ref fDataCreazione, value); }
        }
        DateTime? fDataScadenza;
        public DateTime? DataScadenza
        {
            get { return fDataScadenza; }
            set { SetPropertyValue<DateTime?>(nameof(DataScadenza), ref fDataScadenza, value); }
        }
        string fTitolo;
        public string Titolo
        {
            get { return fTitolo; }
            set { SetPropertyValue<string>(nameof(Titolo), ref fTitolo, value); }
        }
        Modulo fModulo;
        public Modulo Modulo
        {
            get { return fModulo; }
            set { SetPropertyValue<Modulo>(nameof(Modulo), ref fModulo, value); }
        }
    }

}
