//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace xMax.Module.BusinessObjects.Database
{

    public partial class ElencoVerifiche : XPObject
    {
        Attrezzatura fAttrezzatura;
        [Association(@"ElencoVerificheReferencesAttrezzatura")]
        public Attrezzatura Attrezzatura
        {
            get { return fAttrezzatura; }
            set { SetPropertyValue<Attrezzatura>(nameof(Attrezzatura), ref fAttrezzatura, value); }
        }
        string fDescrizione;
        public string Descrizione
        {
            get { return fDescrizione; }
            set { SetPropertyValue<string>(nameof(Descrizione), ref fDescrizione, value); }
        }
        DateTime fData;
        public DateTime Data
        {
            get { return fData; }
            set { SetPropertyValue<DateTime>(nameof(Data), ref fData, value); }
        }
        string fFrequenza;
        public string Frequenza
        {
            get { return fFrequenza; }
            set { SetPropertyValue<string>(nameof(Frequenza), ref fFrequenza, value); }
        }
        DateTime fDataProssimaScadenza;
        public DateTime DataProssimaScadenza
        {
            get { return fDataProssimaScadenza; }
            set { SetPropertyValue<DateTime>(nameof(DataProssimaScadenza), ref fDataProssimaScadenza, value); }
        }
        Dipendente fResponsabile;
        public Dipendente Responsabile
        {
            get { return fResponsabile; }
            set { SetPropertyValue<Dipendente>(nameof(Responsabile), ref fResponsabile, value); }
        }
        string fNote;
        [Size(2048)]
        public string Note
        {
            get { return fNote; }
            set { SetPropertyValue<string>(nameof(Note), ref fNote, value); }
        }
        int fContatoreUtilizzo;
        public int ContatoreUtilizzo
        {
            get { return fContatoreUtilizzo; }
            set { SetPropertyValue<int>(nameof(ContatoreUtilizzo), ref fContatoreUtilizzo, value); }
        }
        int fFrequenzaUtilizzo;
        public int FrequenzaUtilizzo
        {
            get { return fFrequenzaUtilizzo; }
            set { SetPropertyValue<int>(nameof(FrequenzaUtilizzo), ref fFrequenzaUtilizzo, value); }
        }
        int fContatoreProssimaScadenza;
        public int ContatoreProssimaScadenza
        {
            get { return fContatoreProssimaScadenza; }
            set { SetPropertyValue<int>(nameof(ContatoreProssimaScadenza), ref fContatoreProssimaScadenza, value); }
        }
    }

}
