//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace xMax.Module.BusinessObjects.Database
{

    public partial class Fornitore : Anagrafica
    {
        [DevExpress.ExpressApp.Model.ModelDefault("AllowEdit", "False")]
        [DevExpress.Xpo.DisplayName(@"Elenco DDT")]
        [Association(@"DDTAcquistoReferencesFornitore")]
        public XPCollection<DDTAcquisto> ElencoDDT { get { return GetCollection<DDTAcquisto>(nameof(ElencoDDT)); } }
        [Association(@"FornitoreArticoloReferencesFornitore"), Aggregated]
        public XPCollection<FornitoreArticolo> Articoli { get { return GetCollection<FornitoreArticolo>(nameof(Articoli)); } }
    }

}
