//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace xMax.Module.BusinessObjects
{

    public partial class FornitoreArticolo : XPObject
    {
        Articolo fArticolo;
        [Association(@"FornitoreArticoloReferencesArticolo")]
        public Articolo Articolo
        {
            get { return fArticolo; }
            set { SetPropertyValue<Articolo>(nameof(Articolo), ref fArticolo, value); }
        }
        Fornitore fFornitore;
        [Association(@"FornitoreArticoloReferencesFornitore")]
        public Fornitore Fornitore
        {
            get { return fFornitore; }
            set { SetPropertyValue<Fornitore>(nameof(Fornitore), ref fFornitore, value); }
        }
        string fCodiceArticoloFornitore;
        public string CodiceArticoloFornitore
        {
            get { return fCodiceArticoloFornitore; }
            set { SetPropertyValue<string>(nameof(CodiceArticoloFornitore), ref fCodiceArticoloFornitore, value); }
        }
        string fDescrizioneArticoloFornitore;
        [Size(2048)]
        public string DescrizioneArticoloFornitore
        {
            get { return fDescrizioneArticoloFornitore; }
            set { SetPropertyValue<string>(nameof(DescrizioneArticoloFornitore), ref fDescrizioneArticoloFornitore, value); }
        }
    }

}
