//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace xMax.Module.BusinessObjects.Database
{

    public partial class IdoneitaAttestatiFormazione : XPObject
    {
        Dipendente fDipendente;
        [Association(@"IdoneitaAttestatiFormazioneReferencesDipendente")]
        public Dipendente Dipendente
        {
            get { return fDipendente; }
            set { SetPropertyValue<Dipendente>(nameof(Dipendente), ref fDipendente, value); }
        }
        Attestato fAttestato;
        public Attestato Attestato
        {
            get { return fAttestato; }
            set { SetPropertyValue<Attestato>(nameof(Attestato), ref fAttestato, value); }
        }
        string fDataRilascio;
        public string DataRilascio
        {
            get { return fDataRilascio; }
            set { SetPropertyValue<string>(nameof(DataRilascio), ref fDataRilascio, value); }
        }
        string fDataScadenza;
        public string DataScadenza
        {
            get { return fDataScadenza; }
            set { SetPropertyValue<string>(nameof(DataScadenza), ref fDataScadenza, value); }
        }
        short fOreFormazione;
        public short OreFormazione
        {
            get { return fOreFormazione; }
            set { SetPropertyValue<short>(nameof(OreFormazione), ref fOreFormazione, value); }
        }
    }

}
