//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace xMax.Module.BusinessObjects.Database
{

    public partial class Installazione : BaseEvent
    {
        Cliente fCliente;
        [Association(@"InstallazioneReferencesCliente")]
        public Cliente Cliente
        {
            get { return fCliente; }
            set { SetPropertyValue<Cliente>(nameof(Cliente), ref fCliente, value); }
        }
        Apparato fApparato;
        [Association(@"InstallazioneReferencesApparato")]
        public Apparato Apparato
        {
            get { return fApparato; }
            set { SetPropertyValue<Apparato>(nameof(Apparato), ref fApparato, value); }
        }
        string fMatricola;
        public string Matricola
        {
            get { return fMatricola; }
            set { SetPropertyValue<string>(nameof(Matricola), ref fMatricola, value); }
        }
        DateTime fDataInstallazione;
        public DateTime DataInstallazione
        {
            get { return fDataInstallazione; }
            set { SetPropertyValue<DateTime>(nameof(DataInstallazione), ref fDataInstallazione, value); }
        }
        string fCodiceTargaturaCRITER;
        public string CodiceTargaturaCRITER
        {
            get { return fCodiceTargaturaCRITER; }
            set { SetPropertyValue<string>(nameof(CodiceTargaturaCRITER), ref fCodiceTargaturaCRITER, value); }
        }
        DateTime fDataProssimaPulizia;
        public DateTime DataProssimaPulizia
        {
            get { return fDataProssimaPulizia; }
            set { SetPropertyValue<DateTime>(nameof(DataProssimaPulizia), ref fDataProssimaPulizia, value); }
        }
        Contratto fContratto;
        public Contratto Contratto
        {
            get { return fContratto; }
            set { SetPropertyValue<Contratto>(nameof(Contratto), ref fContratto, value); }
        }
        [Association(@"InterventiReferencesInstallazione")]
        public XPCollection<Intervento> Interventi { get { return GetCollection<Intervento>(nameof(Interventi)); } }
    }

}
