//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace xMax.Module.BusinessObjects.xMaxDataModel
{

    public partial class Installazione : XPObject
    {
        Cliente fCliente;
        [Association(@"InstallazioneReferencesCliente")]
        public Cliente Cliente
        {
            get { return fCliente; }
            set { SetPropertyValue<Cliente>(nameof(Cliente), ref fCliente, value); }
        }
        Apparato fApparato;
        [Association(@"InstallazioneReferencesApparato")]
        public Apparato Apparato
        {
            get { return fApparato; }
            set { SetPropertyValue<Apparato>(nameof(Apparato), ref fApparato, value); }
        }
        string fMatricola;
        public string Matricola
        {
            get { return fMatricola; }
            set { SetPropertyValue<string>(nameof(Matricola), ref fMatricola, value); }
        }
        DateTime fDataInizio;
        public DateTime DataInizio
        {
            get { return fDataInizio; }
            set { SetPropertyValue<DateTime>(nameof(DataInizio), ref fDataInizio, value); }
        }
        DateTime fDataScadenza;
        public DateTime DataScadenza
        {
            get { return fDataScadenza; }
            set { SetPropertyValue<DateTime>(nameof(DataScadenza), ref fDataScadenza, value); }
        }
        [Association(@"InterventoReferencesInstallazione")]
        public XPCollection<Intervento> Interventi { get { return GetCollection<Intervento>(nameof(Interventi)); } }
    }

}
