//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace xMax.Module.BusinessObjects
{

    public partial class Intervento : BaseEvent
    {
        Cliente fCliente;
        [Association(@"InterventoReferencesCliente")]
        public Cliente Cliente
        {
            get { return fCliente; }
            set { SetPropertyValue<Cliente>(nameof(Cliente), ref fCliente, value); }
        }
        DateTime fDataIntervento;
        public DateTime DataIntervento
        {
            get { return fDataIntervento; }
            set { SetPropertyValue<DateTime>(nameof(DataIntervento), ref fDataIntervento, value); }
        }
        Dipendente fOperatore;
        public Dipendente Operatore
        {
            get { return fOperatore; }
            set { SetPropertyValue<Dipendente>(nameof(Operatore), ref fOperatore, value); }
        }
        TipoIntervento fTipoIntervento;
        [DevExpress.Persistent.Base.ImmediatePostData]
        public TipoIntervento TipoIntervento
        {
            get { return fTipoIntervento; }
            set { SetPropertyValue<TipoIntervento>(nameof(TipoIntervento), ref fTipoIntervento, value); }
        }
        Installazione fInstallazione;
        [Association(@"InterventoReferencesInstallazione")]
        public Installazione Installazione
        {
            get { return fInstallazione; }
            set { SetPropertyValue<Installazione>(nameof(Installazione), ref fInstallazione, value); }
        }
        tipoFatturaRicevuta fFatturaRicevuta;
        public tipoFatturaRicevuta FatturaRicevuta
        {
            get { return fFatturaRicevuta; }
            set { SetPropertyValue<tipoFatturaRicevuta>(nameof(FatturaRicevuta), ref fFatturaRicevuta, value); }
        }
        string fDescrizioneIntervento;
        [Size(2048)]
        public string DescrizioneIntervento
        {
            get { return fDescrizioneIntervento; }
            set { SetPropertyValue<string>(nameof(DescrizioneIntervento), ref fDescrizioneIntervento, value); }
        }
        decimal fImportoIncassato;
        public decimal ImportoIncassato
        {
            get { return fImportoIncassato; }
            set { SetPropertyValue<decimal>(nameof(ImportoIncassato), ref fImportoIncassato, value); }
        }
        Contratto fContratto;
        [Association(@"InterventoReferencesContratto")]
        public Contratto Contratto
        {
            get { return fContratto; }
            set { SetPropertyValue<Contratto>(nameof(Contratto), ref fContratto, value); }
        }
        string fNote;
        [Size(2048)]
        public string Note
        {
            get { return fNote; }
            set { SetPropertyValue<string>(nameof(Note), ref fNote, value); }
        }
        [Association(@"RicambiUtilizzatiReferencesIntervento"), Aggregated]
        public XPCollection<RicambiUtilizzati> RicambiUtilizzati { get { return GetCollection<RicambiUtilizzati>(nameof(RicambiUtilizzati)); } }
    }

}
