//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace xMax.Module.BusinessObjects
{

    public partial class Modulo : XPObject
    {
        string fDescrizione;
        public string Descrizione
        {
            get { return fDescrizione; }
            set { SetPropertyValue<string>(nameof(Descrizione), ref fDescrizione, value); }
        }
        string fModello;
        public string Modello
        {
            get { return fModello; }
            set { SetPropertyValue<string>(nameof(Modello), ref fModello, value); }
        }
        int fValidità;
        public int Validità
        {
            get { return fValidità; }
            set { SetPropertyValue<int>(nameof(Validità), ref fValidità, value); }
        }
        bool fStampaQRCode;
        public bool StampaQRCode
        {
            get { return fStampaQRCode; }
            set { SetPropertyValue<bool>(nameof(StampaQRCode), ref fStampaQRCode, value); }
        }
    }

}
