//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace xMax.Module.BusinessObjects
{

    public partial class Rischi : XPObject
    {
        string fDescrizione;
        public string Descrizione
        {
            get { return fDescrizione; }
            set { SetPropertyValue<string>(nameof(Descrizione), ref fDescrizione, value); }
        }
        string fPericolo;
        public string Pericolo
        {
            get { return fPericolo; }
            set { SetPropertyValue<string>(nameof(Pericolo), ref fPericolo, value); }
        }
        string fNatura;
        public string Natura
        {
            get { return fNatura; }
            set { SetPropertyValue<string>(nameof(Natura), ref fNatura, value); }
        }
        string fCondizione;
        public string Condizione
        {
            get { return fCondizione; }
            set { SetPropertyValue<string>(nameof(Condizione), ref fCondizione, value); }
        }
        string fProbabilita;
        public string Probabilita
        {
            get { return fProbabilita; }
            set { SetPropertyValue<string>(nameof(Probabilita), ref fProbabilita, value); }
        }
        string fMagnitudo;
        public string Magnitudo
        {
            get { return fMagnitudo; }
            set { SetPropertyValue<string>(nameof(Magnitudo), ref fMagnitudo, value); }
        }
    }

}
