//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace xMax.Module.BusinessObjects
{

    public partial class ScadenzaPagamento : BaseEvent
    {
        Contratto fContratto;
        [Association(@"ScadenzaPagamentoReferencesContratto")]
        public Contratto Contratto
        {
            get { return fContratto; }
            set { SetPropertyValue<Contratto>(nameof(Contratto), ref fContratto, value); }
        }
        DateTime fData;
        public DateTime Data
        {
            get { return fData; }
            set { SetPropertyValue<DateTime>(nameof(Data), ref fData, value); }
        }
        decimal fImporto;
        public decimal Importo
        {
            get { return fImporto; }
            set { SetPropertyValue<decimal>(nameof(Importo), ref fImporto, value); }
        }
    }

}
